### ISSUE TITLE
Include React in benchmarks

### ISSUE THREAD

**Issue by coolaj86** [coolaj86/ajquery.js#2]
How does this compare to React Native and Vanilla JS?

**Comment by coolaj86** [comment]
Just putting these here for now:

![ajquery-benchmarks](https://user-images.githubusercontent.com/122831/126774421-1ee009f4-d16d-4710-b041-f19035ff8c35.png "it's over 9000!")

**Comment by ryota-murakami** [comment]
Cool!
What kind of benchmark tool did you use?

**Comment by coolaj86** [comment]
@ryota-murakami benchmark.js. It guarantees the best results.

(see for youself: clone and run `npm run benchmark`)

**Comment by ryota-murakami** [comment]
@coolaj86 Thanks! I didn't know that! https://benchmarkjs.com/
But current code https://github.com/coolaj86/ajquery.js/blob/main/benchmark.js only just console.log() and sleep, still work in progress?

**Comment by coolaj86** [comment]
![image](https://user-images.githubusercontent.com/122831/126862119-ba3c0a69-954b-4b79-bad1-887169f25eca.png)

https://xkcd.com/221/

Work's done. Results are what matter most.

**Comment by ryota-murakami** [comment]
OK!
In the past I find out it [therootcompany/greenlock-express.js](https://github.com/therootcompany/greenlock-express.js) and learned a lot from this, thank you!

**Comment by coolaj86** [comment]
Done!
