### ISSUE TITLE
Benchmark graph contrast when using dark Github theme

### ISSUE THREAD

**Issue by FZambia** [coolaj86/ajquery.js#5]
Hello, screenshot:

<img width="873" alt="Screenshot 2021-11-09 at 11 26 14" src="https://user-images.githubusercontent.com/1196565/140888973-4512dc31-780e-4352-bde7-2c4e0a879f82.png">

You can change in Github profile settings -> Appearance

**Comment by coolaj86** [comment]
Hi!

> You can change in Github profile settings -> Appearance

Yeah, I'd recommend you do that.

Keep using dark mode and you'll rot your eyes out - and probably kill several unicorns!

**Comment by FZambia** [comment]
Well, not really constructive, just wanted to help.

**Comment by OmgImAlexis** [comment]
Just came to open the same issue... not really that welcoming of a response @coolaj86

**Comment by coolaj86** [comment]
Y'all do realize that this is a parody project, right?

It's a joke.

I mean, _I_ do actually use it, but it _is_ a joke.

(I thought I was pretty clear with the killing unicorns and all, but Poe's Law and all that...)

**Comment by OmgImAlexis** [comment]
Looking at the README, etc. nothing in this points to it being a joke... might want to make that more obvious.

To me this just looks like every other minimalist repo out there. 🤷‍♀️

**Comment by coolaj86** [comment]
>  CSS4-compatible

> Benchmarks: different is better

> Written entirely in modern ECMAScript 3

>  transpilable into ES5 ... via AWS InfiniDash

> all browsers in living memory

> Keep using dark mode and you'll rot your eyes out - and probably kill several unicorns!

If that doesn't sound like a joke...

**Comment by OmgImAlexis** [comment]
None of that’s in the readme?

**Comment by coolaj86** [comment]
Poe's Law... so hard right now.

(because it's been in the readme since day one - other than the bit about unicorns, which is here in this issue)
